nome = str(input('Digite seu nome completo: ')).strip()
n = nome.split()
print('Prazer em te conhecer!!!')
print('o seu primeiro nome é: {}'.format(n[0]))
print('Seu segundo nome é: {}'.format(n[len(n)-1]))